# # Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# # More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy dotnet core project to Azure Function App - hrd-csharp-azfunction-devops-git

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# env:
#   AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
#   DOTNET_VERSION: '8.0' # set this to the dotnet version to use

# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       id-token: write #This is required for requesting the JWT
#       contents: read #This is required for actions/checkout

#     steps:
#       - name: 'Checkout GitHub Action'
#         uses: actions/checkout@v4

#       - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
#         uses: actions/setup-dotnet@v1
#         with:
#           dotnet-version: ${{ env.DOTNET_VERSION }}

#       - name: 'Resolve Project Dependencies Using Dotnet'
#         shell: bash
#         run: |
#           pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
#           dotnet build --configuration Release --output ./output
#           popd
      
#       - name: Login to Azure
#         uses: azure/login@v2
#         with:
#           client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B028078B8577415A8D9F4939555541F7 }}
#           tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AB4D3FFEDADE48349118FA22DAAD8BE8 }}
#           subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_29FC44436E5A44C9B537104F9C25AA71 }}

#       - name: 'Run Azure Functions Action'
#         uses: Azure/functions-action@v1
#         id: fa
#         with:
#           app-name: 'hrd-csharp-azfunction-devops-git'
#           slot-name: 'Production'
#           package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
          


# Docs: https://github.com/azure/functions-action

name: Build and deploy .NET Azure Function App - hrd-csharp-azfunction-devops-git

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'  # path to your Function project
  DOTNET_VERSION: '8.0'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4

      - name: 'Setup .NET ${{ env.DOTNET_VERSION }}'
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}


      

      - name: 'Publish Azure Function App'
        shell: bash
        run: dotnet publish -c Release --property PublishDir=${{ github.workspace }}/drop
        # run: |
        #   pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
        #   dotnet publish -c Release --output ${{ github.workspace }}/drop
        #   popd

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          include-hidden-files: true
          path: ${{env.AZURE_FUNCTIONAPP_PACKAGE_PATH}}

      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_B028078B8577415A8D9F4939555541F7 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AB4D3FFEDADE48349118FA22DAAD8BE8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_29FC44436E5A44C9B537104F9C25AA71 }}

      - name: 'Deploy to Azure Function App'
        uses: Azure/functions-action@v1
        with:
          app-name: 'hrd-csharp-azfunction-devops-git'
          slot-name: 'Production'
          package: '${{ github.workspace }}/drop'
